export const Action_type={
    ADD_ELEMENT_TO_REDUX:'ADD_ELEMENT_TO_REDUX',
    SET_USER_CREDENTIAL:'SET_USER_CREDENTIAL',
    FETCH_API_SUCCESSFULLY:"FETCH_API_SUCCESSFULLY",
    SET_API_FETCH_ERROR:'SET_API_FETCH_ERROR',
    SET_USER_ADDRESS:'SET_USER_ADDRESS',
    SET_HORIZONTAL_DATA:'SET_HORIZONTAL_DATA',
    SET_VERTICAL_DATA:'SET_VERTICAL_DATA',
    SET_HORIZONTAL_SELECTED_DATA:'SET_HORIZONTAL_SELECTED_DATA',
    ADD_ITEM_TO_CART:'ADD_ITEM_TO_CART'

}